### ISSUE TITLE
Cannot import spherecluster with scikit-learn 1.0.2: sklearn.cluster.k_means_ has been renamed

### ISSUE THREAD

**Issue by ngiatsog** [jasonlaska/spherecluster#35]
The traceback is
 
Traceback (most recent call last):
  File "/<xxx>/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-6b21f49e6e06>", line 1, in <module>
    import spherecluster
  File "/snap/pycharm-community/267/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/<xxx>/python3.9/site-packages/spherecluster/__init__.py", line 2, in <module>
    from .spherical_kmeans import SphericalKMeans
  File "/snap/pycharm-community/267/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/<xxx>/python3.9/site-packages/spherecluster/spherical_kmeans.py", line 7, in <module>
    from sklearn.cluster.k_means_ import (
  File "/snap/pycharm-community/267/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'sklearn.cluster.k_means_'

The problem is that 'sklearn.cluster.k_means_' has been renamed to 'sklearn.cluster._kmeans' in some intermediate scikit-learn version.

**Comment by rfayat** [comment]
Hi !

I haven't tested it with the most recent version of scikit but I solved this issue for scikit 0.24 in my pull request #34 (you can also check [my fork](https://github.com/rfayat/spherecluster)) where the change from `sklearn.cluster.k_means_` to `sklearn.cluster._kmeans` appeared.

From what I remember it was a bit more complicated than a simple renaming issue because some functions called by `sklearn.cluster.k_means_` are now class methods of `KMeans`.

Hope this helps !

Romain

**Comment by Darel13712** [comment]
@rfayat Hey, I tried your version, but ran into 
```
from sklearn.cluster import _k_means_fast as _k_means

ImportError: cannot import name '_k_means_fast' from 'sklearn.cluster'
```

Does it mean that interfaces changed once again or I'm just using a wrong version?

**Comment by rfayat** [comment]
Hey @Darel13712 indeed I just checked and it seems to have changed again between v0.24 and V1.0.2, my fork won't work for this newest version...

Sorry for the false hope :disappointed: 

Cheers,

RF

**Comment by yuye-aws** [comment]
Also meet with the same problem. Is there any workaround to train spherical kmeans?

**Comment by mostlyworking** [comment]
> Also meet with the same problem. Is there any workaround to train spherical kmeans?

One workaround is to use Faiss library, which has a `spherical` parameter for their K-means implementation:
https://github.com/facebookresearch/faiss/wiki/Faiss-building-blocks:-clustering,-PCA,-quantization
